# Generated by Django 3.0.6 on 2020-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200508_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='calculated_price',
        ),
    ]
